### ISSUE TITLE
Opening GroupMe should reuse tabs

### ISSUE THREAD

**Issue by dmihal** [dmihal/GroupMe-Notifier#3]
If the user clicks a notification, and there's already an open groupme tab, it should open in that tab

**Comment by OJ7** [comment]
Hey I found this project and seems like exactly what I want (since GroupMe isn't adding this feature)!
Been using Pushbullet from phone to get notifications but having the same issue as this.

I'm going to try to find some free time so I can help you look into fixing this.

**Comment by dmihal** [comment]
@OJ7 Great to hear! I also use Pushbullet, but started this project since I wanted better GroupMe notifications.

Right now, #4 is the biggest issue that's preventing the extension from working correctly

**Comment by OJ7** [comment]
So this looked like a good idea and almost got it working:
http://stackoverflow.com/questions/25661543/how-to-know-if-browser-tab-is-already-open-using-javascript

A few problems:
- this only opens existing tab/window if it was created from clicking the notification (i.e. does not open in tab that was manually opened)
- I get some js errors when loading the groupme page. It does not load the chats and just has the loading # icon. Here's the error message I get "Uncaught SecurityError: Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes." Still trying to figure out why that error occurs.
  You can test it out using this: http://jsbin.com/luhosukolu/1/edit?html,js,output

EDIT: I believe that these problems can be circumvented by using chrome.tabs (https://developer.chrome.com/extensions/tabs)

**Comment by OJ7** [comment]
Also just browsing around, some suggestions say to use "session/local storage". However, I'm unfamiliar with it and would have to look into it further.

**Comment by dmihal** [comment]
Since this is a Chrome Extension, Chrome gives us a bunch more APIs that can be use, this issue will probably involve the [`chrome.tabs`](https://developer.chrome.com/extensions/tabs) APIs. 

[This project](https://github.com/rjregenold/reusetab-chrome) might have some useful code to look at.

**Comment by OJ7** [comment]
Yep just edited my previous comment to include that. Working on adding it now...

**Comment by OJ7** [comment]
So I made changes in my fork for this feature but for some reason I can't log in (no popup appears) when packaging my code. See if it works on your end.

Btw, I did a pretty messy solution just for testing. You can use the project you mentioned above as that is prob more efficient.

**Comment by dmihal** [comment]
Try pulling my development branch, your issue should have been fixed in 617bb4314b5b143ec24ad72ee56d2a23b30409d5

**Comment by dmihal** [comment]
Added in #7
